logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: eureka-api
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-start
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://eureka:8761
          predicates:
            - Path=/eureka/**

        - id: movie-catalog
          uri: lb://movie-catalog
          predicates:
            - Path=/movies/**

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"